services:
  rethinkdb:
    image: rethinkdb:latest
    volumes:
      - appserver_database:/data
    ports:
      - 6403:8080
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -sS http://localhost:8080/ > /dev/null"]
      interval: 1s
      timeout: 1s
      retries: 20

  backend:
    build:
      context: backend
    ports:
      - 6401:3000
    depends_on:
      rethinkdb:
        condition: service_healthy

volumes:
  appserver_database: